// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmjeucqklloszbqmgjkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtamV1Y3FrbGxvc3picW1namtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MTgyNzksImV4cCI6MjA1Mzk5NDI3OX0.SWXVNmH9kvcA3dRPOpvClkaMvYr7tOaV78UPU2hROSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);